import type { Metadata } from "next";
import { Inter,  Plaster} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const plaster = Plaster({
  weight: '400', // Specify the desired font weight
  subsets: ['latin'],
  display: 'swap',
  variable: '--fplaster',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
