import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import CekLogin from '@/components/cekLoginComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <CekLogin> */}
          {children}
        {/* </CekLogin> */}
      </body>
    </html>
  )
}
