import type { Metadata } from 'next'
import './globals.css'
import MasterDashboardComponent from '@/components/MasterDashboardComponent'
import { Manrope } from 'next/font/google'
 
const manrope = Manrope({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <MasterDashboardComponent>
          {children}
        </MasterDashboardComponent>
      </body>
    </html>
  )
}

